#!/usr/bin/python2
#
# Test suite for PyCorewar
#
# Copyright (C) 2005-2006 Jens Gutzeit <jens@jgutzeit.de>
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

import unittest
import Test.Redcode
import Test.Instruction88
import Test.BenchmarkingMARS88

if __name__ == '__main__':
    # Build testsuite. 
    tests = []
   
    tests.append(unittest.makeSuite(Test.Redcode.TestCase)) 
    tests.append(unittest.makeSuite(Test.Instruction88.TestCase))
    tests.append(unittest.makeSuite(Test.BenchmarkingMARS88.TestCase))
    
    allTests = unittest.TestSuite(tests)

    # Run testsuite.
    unittest.TextTestRunner(verbosity=2).run(allTests)
